# Databricks notebook source
# MAGIC %md 
# MAGIC # DATAFRAMES

# COMMAND ----------

# MAGIC %md
# MAGIC 
# MAGIC ## CREATE DATAFRAME
# MAGIC 
# MAGIC 
# MAGIC we can create dataframes with dummy data, for it, we need to create a `RDD` as base. Example:

# COMMAND ----------

columns = ["language", "type", "supported_by_spark", "bool_type"]
data = [
    ("java", "compiled", "y", 1), 
    ("python", "interpreted", "y", 1), 
    ("Scala", "compiled", "y", 1),
    ("r", "interpreted", "y", 1), 
    ("powerbuilder", "unknow", "n", 0), 
    ("c++", "compiled", "n", 0)
]

rdd = spark.sparkContext.parallelize(data)
rdd.take(6)

# COMMAND ----------

# MAGIC %md
# MAGIC 
# MAGIC ### TODF
# MAGIC 
# MAGIC by de fault due that we don't approvisionated schema, spark infer the colum names an data types

# COMMAND ----------

# MAGIC %md
# MAGIC 
# MAGIC #### WITHOUT COLUMN NAMES

# COMMAND ----------

df_without_columns = rdd.toDF()
df_without_columns.printSchema()

# COMMAND ----------

# MAGIC %md
# MAGIC 
# MAGIC #### WITH COLUMN NAMES

# COMMAND ----------

df_with_columns = rdd.toDF(columns)
df_with_columns.printSchema()

# COMMAND ----------

# MAGIC %md
# MAGIC 
# MAGIC ### CREATE DATAFRAME

# COMMAND ----------

# MAGIC %md
# MAGIC 
# MAGIC #### WITHOUT SCHEMA

# COMMAND ----------

create_df_nc_ns = spark.createDataFrame(data)
create_df_nc_ns.printSchema()

# COMMAND ----------

# MAGIC %md
# MAGIC 
# MAGIC #### WITH COLUMN NAMES

# COMMAND ----------

create_df_yc_ns = spark.createDataFrame(data).toDF(*columns)
create_df_yc_ns.printSchema()

# COMMAND ----------

# MAGIC %md
# MAGIC 
# MAGIC #### WITH ROW TYPE

# COMMAND ----------

from pyspark.sql.types import Row
row_data = map(lambda row: Row(*row), data) 
create_df_row = spark.createDataFrame(row_data,columns)
create_df_row.printSchema()

# COMMAND ----------

# MAGIC %md
# MAGIC 
# MAGIC #### CREATE DATAFRAME WITH SCHEMA
# MAGIC 
# MAGIC ```
# MAGIC StructField ("column-name", "data type", "nullable", )
# MAGIC ```

# COMMAND ----------

from pyspark.sql.types import StructType, StructField, StringType, ByteType

schema = StructType([
    StructField("language",StringType(), False),
    StructField("type",StringType(), True),
    StructField("supported",StringType()),
    StructField("logic_type",ByteType(), False)
])

create_df_yc_ys = spark.createDataFrame(data=data, schema=schema)
create_df_yc_ys.printSchema()

# COMMAND ----------

# MAGIC %md
# MAGIC 
# MAGIC ## READ

# COMMAND ----------

# MAGIC %md
# MAGIC #### CSV
# MAGIC 
# MAGIC **DATASET OVERVIEW**
# MAGIC 
# MAGIC 
# MAGIC 
# MAGIC 
# MAGIC 
# MAGIC 
# MAGIC 
# MAGIC 
# MAGIC **CSV OPTIONS**
# MAGIC 
# MAGIC from https://spark.apache.org/docs/latest/sql-data-sources-csv.html
# MAGIC 
# MAGIC 
# MAGIC | Property Name             | Default                                                      | Meaning                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | Scope      |
# MAGIC |---------------------------|--------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
# MAGIC | sep                       | ,                                                            | Sets a separator for each field and value. This separator can be one or more characters.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | read/write |
# MAGIC | encoding                  | UTF-8                                                        | For reading, decodes the CSV files by the given encoding type. For writing, specifies encoding (charset) of saved CSV files. CSV built-in functions ignore this option.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | read/write |
# MAGIC | quote                     | "                                                            | Sets a single character used for escaping quoted values where the separator can be part of the value. For reading, if you would like to turn off quotations, you need to set not null but an empty string. For writing, if an empty string is set, it uses u0000 (null character).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | read/write |
# MAGIC | quoteAll                  | false                                                        | A flag indicating whether all values should always be enclosed in quotes. Default is to only escape values containing a quote character.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | write      |
# MAGIC | escape                    | \                                                            | Sets a single character used for escaping quotes inside an already quoted value.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | read/write |
# MAGIC | escapeQuotes              | true                                                         | A flag indicating whether values containing quotes should always be enclosed in quotes. Default is to escape all values containing a quote character.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | write      |
# MAGIC | comment                   |                                                              | Sets a single character used for skipping lines beginning with this character. By default, it is disabled.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | read       |
# MAGIC | header                    | false                                                        | For reading, uses the first line as names of columns. For writing, writes the names of columns as the first line. Note that if the given path is a RDD of Strings, this header option will remove all lines same with the header if exists. CSV built-in functions ignore this option.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | read/write |
# MAGIC | inferSchema               | false                                                        | Infers the input schema automatically from data. It requires one extra pass over the data. CSV built-in functions ignore this option.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | read       |
# MAGIC | enforceSchema             | true                                                         | If it is set to true, the specified or inferred schema will be forcibly applied to datasource files, and headers in CSV files will be ignored. If the option is set to false, the schema will be validated against all headers in CSV files in the case when the header option is set to true. Field names in the schema and column names in CSV headers are checked by their positions taking into account spark.sql.caseSensitive. Though the default value is true, it is recommended to disable the enforceSchema option to avoid incorrect results. CSV built-in functions ignore this option.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | read       |
# MAGIC | ignoreLeadingWhiteSpace   | false (for reading), true (for writing)                      | A flag indicating whether or not leading whitespaces from values being read/written should be skipped.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | read/write |
# MAGIC | ignoreTrailingWhiteSpace  | false (for reading), true (for writing)                      | A flag indicating whether or not trailing whitespaces from values being read/written should be skipped.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | read/write |
# MAGIC | nullValue                 |                                                              | Sets the string representation of a null value. Since 2.0.1, this nullValue param applies to all supported types including the string type.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | read/write |
# MAGIC | nanValue                  | NaN                                                          | Sets the string representation of a non-number value.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | read       |
# MAGIC | positiveInf               | Inf                                                          | Sets the string representation of a positive infinity value.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | read       |
# MAGIC | negativeInf               | -Inf                                                         | Sets the string representation of a negative infinity value.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | read       |
# MAGIC | dateFormat                | yyyy-MM-dd                                                   | Sets the string that indicates a date format. Custom date formats follow the formats at Datetime Patterns. This applies to date type.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | read/write |
# MAGIC | timestampFormat           | yyyy-MM-dd'T'HH:mm:ss[.SSS][XXX]                             | Sets the string that indicates a timestamp format. Custom date formats follow the formats at Datetime Patterns. This applies to timestamp type.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | read/write |
# MAGIC | timestampNTZFormat        | yyyy-MM-dd'T'HH:mm:ss[.SSS]                                  | Sets the string that indicates a timestamp without timezone format. Custom date formats follow the formats at Datetime Patterns. This applies to timestamp without timezone type, note that zone-offset and time-zone components are not supported when writing or reading this data type.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | read/write |
# MAGIC | maxColumns                | 20480                                                        | Defines a hard limit of how many columns a record can have.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | read       |
# MAGIC | maxCharsPerColumn         | -1                                                           | Defines the maximum number of characters allowed for any given value being read. By default, it is -1 meaning unlimited length                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | read       |
# MAGIC | mode                      | PERMISSIVE                                                   | Allows a mode for dealing with corrupt records during parsing. It supports the following case-insensitive modes. Note that Spark tries to parse only required columns in CSV under column pruning. Therefore, corrupt records can be different based on required set of fields. This behavior can be controlled by spark.sql.csv.parser.columnPruning.enabled (enabled by default).  PERMISSIVE: when it meets a corrupted record, puts the malformed string into a field configured by columnNameOfCorruptRecord, and sets malformed fields to null. To keep corrupt records, an user can set a string type field named columnNameOfCorruptRecord in an user-defined schema. If a schema does not have the field, it drops corrupt records during parsing. A record with less/more tokens than schema is not a corrupted record to CSV. When it meets a record having fewer tokens than the length of the schema, sets null to extra fields. When the record has more tokens than the length of the schema, it drops extra tokens. DROPMALFORMED: ignores the whole corrupted records. This mode is unsupported in the CSV built-in functions. FAILFAST: throws an exception when it meets corrupted records. | read       |
# MAGIC | columnNameOfCorruptRecord | (value of spark.sql.columnNameOfCorruptRecord configuration) | Allows renaming the new field having malformed string created by PERMISSIVE mode. This overrides spark.sql.columnNameOfCorruptRecord.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | read       |
# MAGIC | multiLine                 | false                                                        | Parse one record, which may span multiple lines, per file. CSV built-in functions ignore this option.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | read       |
# MAGIC | charToEscapeQuoteEscaping | escape or \0                                                 | Sets a single character used for escaping the escape for the quote character. The default value is escape character when escape and quote characters are different, \0 otherwise.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | read/write |
# MAGIC | samplingRatio             | 1.0                                                          | Defines fraction of rows used for schema inferring. CSV built-in functions ignore this option.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | read       |
# MAGIC | emptyValue                | (for reading), "" (for writing)                              | Sets the string representation of an empty value.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | read/write |
# MAGIC | locale                    | en-US                                                        | Sets a locale as language tag in IETF BCP 47 format. For instance, this is used while parsing dates and timestamps.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | read       |
# MAGIC | lineSep                   | \r, \r\n and \n (for reading), \n (for writing)              | Defines the line separator that should be used for parsing/writing. Maximum length is 1 character. CSV built-in functions ignore this option.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | read/write |
# MAGIC | unescapedQuoteHandling    | STOP_AT_DELIMITER                                            | Defines how the CsvParser will handle values with unescaped quotes.  STOP_AT_CLOSING_QUOTE: If unescaped quotes are found in the input, accumulate the quote character and proceed parsing the value as a quoted value, until a closing quote is found. BACK_TO_DELIMITER: If unescaped quotes are found in the input, consider the value as an unquoted value. This will make the parser accumulate all characters of the current parsed value until the delimiter is found. If no delimiter is found in the value, the parser will continue accumulating characters from the input until a delimiter or line ending is found. STOP_AT_DELIMITER: If unescaped quotes are found in the input, consider the value as an unquoted value. This will make the parser accumulate all characters until the delimiter or a line ending is found in the input. SKIP_VALUE: If unescaped quotes are found in the input, the content parsed for the given value will be skipped and the value set in nullValue will be produced instead. RAISE_ERROR: If unescaped quotes are found in the input, a TextParsingException will be thrown.                                                                                | read       |
# MAGIC | compression               | (none)                                                       | Compression codec to use when saving to file. This can be one of the known case-insensitive shorten names (none, bzip2, gzip, lz4, snappy and deflate). CSV built-in functions ignore this option.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | write      |

# COMMAND ----------



# COMMAND ----------

# MAGIC %md
# MAGIC ####  PARQUET
# MAGIC 
# MAGIC from https://spark.apache.org/docs/latest/sql-data-sources-parquet.html
# MAGIC 
# MAGIC 
# MAGIC | Property Name      | Default                                                             | Meaning                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | Scope |
# MAGIC |--------------------|---------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------|
# MAGIC | datetimeRebaseMode | (value of spark.sql.parquet.datetimeRebaseModeInRead configuration) | The datetimeRebaseMode option allows to specify the rebasing mode for the values of the DATE, TIMESTAMP_MILLIS, TIMESTAMP_MICROS logical types from the Julian to Proleptic Gregorian calendar. Currently supported modes are: EXCEPTION: fails in reads of ancient dates/timestamps that are ambiguous between the two calendars. CORRECTED: loads dates/timestamps without rebasing. LEGACY: performs rebasing of ancient dates/timestamps from the Julian to Proleptic Gregorian calendar. | read  |
# MAGIC | int96RebaseMode    | (value of spark.sql.parquet.int96RebaseModeInRead configuration)    | The int96RebaseMode option allows to specify the rebasing mode for INT96 timestamps from the Julian to Proleptic Gregorian calendar. Currently supported modes are: EXCEPTION: fails in reads of ancient INT96 timestamps that are ambiguous between the two calendars. CORRECTED: loads INT96 timestamps without rebasing. LEGACY: performs rebasing of ancient timestamps from the Julian to Proleptic Gregorian calendar.                                                                  | read  |
# MAGIC | mergeSchema        | (value of spark.sql.parquet.mergeSchema configuration)              | Sets whether we should merge schemas collected from all Parquet part-files. This will override spark.sql.parquet.mergeSchema.                                                                                                                                                                                                                                                                                                                                                                 | read  |
# MAGIC | compression        | snappy                                                              | Compression codec to use when saving to file. This can be one of the known case-insensitive shorten names (none, uncompressed, snappy, gzip, lzo, brotli, lz4, and zstd). This will override spark.sql.parquet.compression.codec.                                                                                                                                                                                                                                                             | write |

# COMMAND ----------

CREATE TABLE test_parquet_2(
name STRING,
email STRING,
country STRING)
USING PARQUET
OPTIONS (
  compression="snappy",
  path='/mnt/bronze/table_parquet_2'
 );

# COMMAND ----------

# MAGIC %md
# MAGIC ####  JSON
# MAGIC from https://spark.apache.org/docs/latest/sql-data-sources-json.html
# MAGIC 
# MAGIC 
# MAGIC | Property Name                      | Default                                                                                 | Meaning                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Scope      |
# MAGIC |------------------------------------|-----------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
# MAGIC | timeZone                           | (value of spark.sql.session.timeZone configuration)                                     | Sets the string that indicates a time zone ID to be used to format timestamps in the JSON datasources or partition values. The following formats of timeZone are supported:  Region-based zone ID: It should have the form 'area/city', such as 'America/Los_Angeles'. Zone offset: It should be in the format '(+\|-)HH:mm', for example '-08:00' or '+01:00'. Also 'UTC' and 'Z' are supported as aliases of '+00:00'.Other short names like 'CST' are not recommended to use because they can be ambiguous.                                                                                                                                                                                                        | read/write |
# MAGIC | primitivesAsString                 | false                                                                                   | Infers all primitive values as a string type.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | read       |
# MAGIC | prefersDecimal                     | false                                                                                   | Infers all floating-point values as a decimal type. If the values do not fit in decimal, then it infers them as doubles.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | read       |
# MAGIC | allowComments                      | false                                                                                   | Ignores Java/C++ style comment in JSON records.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | read       |
# MAGIC | allowUnquotedFieldNames            | false                                                                                   | Allows unquoted JSON field names.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | read       |
# MAGIC | allowSingleQuotes                  | true                                                                                    | Allows single quotes in addition to double quotes.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | read       |
# MAGIC | allowNumericLeadingZero            | false                                                                                   | Allows leading zeros in numbers (e.g. 00012).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | read       |
# MAGIC | allowBackslashEscapingAnyCharacter | false                                                                                   | Allows accepting quoting of all character using backslash quoting mechanism.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | read       |
# MAGIC | mode                               | PERMISSIVE                                                                              | Allows a mode for dealing with corrupt records during parsing.  PERMISSIVE: when it meets a corrupted record, puts the malformed string into a field configured by columnNameOfCorruptRecord, and sets malformed fields to null. To keep corrupt records, an user can set a string type field named columnNameOfCorruptRecord in an user-defined schema. If a schema does not have the field, it drops corrupt records during parsing. When inferring a schema, it implicitly adds a columnNameOfCorruptRecord field in an output schema. DROPMALFORMED: ignores the whole corrupted records. This mode is unsupported in the JSON built-in functions. FAILFAST: throws an exception when it meets corrupted records. | read       |
# MAGIC | columnNameOfCorruptRecord          | (value of spark.sql.columnNameOfCorruptRecord configuration)                            | Allows renaming the new field having malformed string created by PERMISSIVE mode. This overrides spark.sql.columnNameOfCorruptRecord.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | read       |
# MAGIC | dateFormat                         | yyyy-MM-dd                                                                              | Sets the string that indicates a date format. Custom date formats follow the formats at datetime pattern. This applies to date type.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | read/write |
# MAGIC | timestampFormat                    | yyyy-MM-dd'T'HH:mm:ss[.SSS][XXX]                                                        | Sets the string that indicates a timestamp format. Custom date formats follow the formats at datetime pattern. This applies to timestamp type.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | read/write |
# MAGIC | timestampNTZFormat                 | yyyy-MM-dd'T'HH:mm:ss[.SSS]                                                             | Sets the string that indicates a timestamp without timezone format. Custom date formats follow the formats at Datetime Patterns. This applies to timestamp without timezone type, note that zone-offset and time-zone components are not supported when writing or reading this data type.                                                                                                                                                                                                                                                                                                                                                                                                                            | read/write |
# MAGIC | multiLine                          | false                                                                                   | Parse one record, which may span multiple lines, per file. JSON built-in functions ignore this option.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | read       |
# MAGIC | allowUnquotedControlChars          | false                                                                                   | Allows JSON Strings to contain unquoted control characters (ASCII characters with value less than 32, including tab and line feed characters) or not.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | read       |
# MAGIC | encoding                           | Detected automatically when multiLine is set to true (for reading), UTF-8 (for writing) | For reading, allows to forcibly set one of standard basic or extended encoding for the JSON files. For example UTF-16BE, UTF-32LE. For writing, Specifies encoding (charset) of saved json files. JSON built-in functions ignore this option.                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | read/write |
# MAGIC | lineSep                            | \r, \r\n, \n (for reading), \n (for writing)                                            | Defines the line separator that should be used for parsing. JSON built-in functions ignore this option.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | read/write |
# MAGIC | samplingRatio                      | 1.0                                                                                     | Defines fraction of input JSON objects used for schema inferring.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | read       |
# MAGIC | dropFieldIfAllNull                 | false                                                                                   | Whether to ignore column of all null values or empty array/struct during schema inference.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | read       |
# MAGIC | locale                             | en-US                                                                                   | Sets a locale as language tag in IETF BCP 47 format. For instance, locale is used while parsing dates and timestamps.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | read       |
# MAGIC | allowNonNumericNumbers             | true                                                                                    | Allows JSON parser to recognize set of “Not-a-Number” (NaN) tokens as legal floating number values.  +INF: for positive infinity, as well as alias of +Infinity and Infinity. -INF: for negative infinity, alias -Infinity. NaN: for other not-a-numbers, like result of division by zero.                                                                                                                                                                                                                                                                                                                                                                                                                            | read       |
# MAGIC | compression                        | (none)                                                                                  | Compression codec to use when saving to file. This can be one of the known case-insensitive shorten names (none, bzip2, gzip, lz4, snappy and deflate). JSON built-in functions ignore this option.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | write      |
# MAGIC | ignoreNullFields                   | (value of spark.sql.jsonGenerator.ignoreNullFields configuration)                       | Whether to ignore null fields when generating JSON objects.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | write      |
# MAGIC |                                    |                                                                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |            |

# COMMAND ----------

# MAGIC %md
# MAGIC ####  AVRO
# MAGIC from https://spark.apache.org/docs/latest/sql-data-sources-json.html

# COMMAND ----------

# MAGIC %md
# MAGIC ####  CRC
# MAGIC from https://spark.apache.org/docs/latest/sql-data-sources-json.html
